@main def hello(): Unit =
//  val day = Day1()
//  println(day.soln1(Utils.readFileAsList("d1.txt")))
//  val s = Utils.readFileAsList("d1.txt")
//  val start = System.nanoTime()
//  val soln = day.soln1(s)
//  val stop = System.nanoTime()
//  println(soln)
//  println(s"${(stop-start)/1000} microseconds")
//  val day2 = Day1v2
//  println(day2.soln(Utils.readFileAsList("d1.txt")))
//  println(Day2.soln1(Utils.readFileAsList("d2.txt")))
//  println(Day2.soln2(Utils.readFileAsList("d2.txt")))
//  println(Day3.soln1(Utils.readFileAsList("d3.txt")))
//  println(Day4.soln1(Utils.readFileAsList("test.txt")))
//  println(Day4.soln1(Utils.readFileAsList("d4.txt")))
//  println(Day9.soln1(Utils.readFileAsList("test.txt")))
  println(Day9.soln1(Utils.readFileAsList("d9.txt")))
//  println(Day9.soln2(Utils.readFileAsList("test.txt")))
  println(Day9.soln2(Utils.readFileAsList("d9.txt")))
//  println(Day15.soln1("rn=1,cm-,qp=3,cm=2,qp-,pc=4,ot=9,ab=5,pc-,pc=6,ot=7"))
//  println(Day15.soln1("cm"))
//  println(Day15.soln1(Utils.readFileFirstLineAsString("d15.txt")))
//  println(Day15.soln2(Utils.readFileFirstLineAsString("d15.txt")))
//  println(Day15.soln2("rn=1,cm-,qp=3,cm=2,qp-,pc=4,ot=9,ab=5,pc-,pc=6,ot=7"))

def msg = "I was compiled by Scala 3. :)"
